Models/AgendamentoModel.cs
using Agendamento_de_Eventos.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

namespace Agendamento_de_Eventos.Models
{
    public class AgendamentoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime DataEvento { get; set; }
        public DuracaoEvento Duracao { get; set; }
        public TipoEvento TipoEvento { get; set; }
        public string NumeroCelular { get; set; }
        public string Localizacao {  get; set; }
        public string? InfoEvento {  get; set; }
        public StatusEvento Status { get; set; }
        public TimeSpan Horainicio { get; set; }
    }
}

Controllers/AdmController.cs
using Agendamento_de_Eventos.Data;
using Agendamento_de_Eventos.Enums;
using Agendamento_de_Eventos.Filters;
using Agendamento_de_Eventos.Helpers;
using Agendamento_de_Eventos.Models;
using Agendamento_de_Eventos.Repositorio;
using Agendamento_de_Eventos.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace Agendamento_de_Eventos.Controllers
{
    public class AdmController : Controller
    {
        private readonly InterfaceAgendamento _interfaceAgendamento;
        private readonly IConfiguration _iconfiguration;

        public AdmController (InterfaceAgendamento interfaceAgendamento, IConfiguration configuration)
        {
            _interfaceAgendamento = interfaceAgendamento;
            _iconfiguration = configuration;
        }


        [ServiceFilter(typeof(AdminAutorizacaoFilter))]
        public IActionResult Index()
        {
            List<AgendamentoModel> agendas = _interfaceAgendamento.BuscarAgendas();

            ViewBag.NewNameDuracao = AlterNameEnum.AlterNameDuracao;
            ViewBag.NewNameTipoEvento = AlterNameEnum.AlterNameTipoEvento;

            return View(agendas);
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult PageMensagemRestrita()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Login(LoginAdmViewModel loginAdm)
        {
            var userConfig = _iconfiguration["LoginAdm:Usuario"];
            var senhaConfig = _iconfiguration["LoginAdm:Senha"];

            if (!ModelState.IsValid)
            {
                TempData["ErrorLoginAdm"] = "Campo usuário e/ou senha não preenchidos. Por favor, preencha os campos.";
                return View("Login", loginAdm);
            }

            if (loginAdm.usuario == userConfig && loginAdm.senha == senhaConfig)
            {
                HttpContext.Session.SetInt32("AdmLogado", 1);
                return RedirectToAction("Index");
            }
            return RedirectToAction("PageMensagemRestrita");
        }

        [HttpPost]
        public IActionResult AtualizarStatus(int id, StatusEvento statusEvento)
        {
            AgendamentoModel agendamento = _interfaceAgendamento.BuscarId(id);

            if (agendamento == null)
            {
                TempData["AgendaNull"] = "Agendamento não Encontrado!";
                return RedirectToAction("Index");
            }

            agendamento.Status = statusEvento;
            _interfaceAgendamento.Atualizar(agendamento);

            TempData["SucessAgendaStatus"] = "Status do evento alterado com sucesso!!";
            return RedirectToAction("Index");
        }
    }
}

Controllers/AgendamentoController.cs
using Agendamento_de_Eventos.Data;
using Agendamento_de_Eventos.Enums;
using Agendamento_de_Eventos.Helpers;
using Agendamento_de_Eventos.Models;
using Agendamento_de_Eventos.Repositorio;
using Agendamento_de_Eventos.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using System.Globalization;

namespace Agendamento_de_Eventos.Controllers
{
    public class AgendamentoController : Controller
    {
        private readonly InterfaceAgendamento _interface;
        private readonly BancoContext _bancoContext;

        public AgendamentoController (InterfaceAgendamento interfaceAgendamento, BancoContext banco)
        {
            _interface = interfaceAgendamento;
            _bancoContext = banco;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEvento (AgendamentoViewModel agendamento)
        {

            if (!ModelState.IsValid)
            {
                TempData["ErroDataModel"] = "Erro ao agendar o evento. Tente Novamente!";
                return View("Index", agendamento);
            }

            var dataReservada = _bancoContext.Agendamento
             .FirstOrDefault(x => x.DataEvento == agendamento.DataMarcada);

            if (dataReservada != null)
            {
                TempData["dataReservada"] = "A data informada já está reservada. Por gentileza escolha outra.";
                return View("Index", agendamento);
            }

                var agendamentoModel = new AgendamentoModel
                {
                    Nome = agendamento.Nome,
                    DataEvento = (DateTime)agendamento.DataMarcada,
                    Duracao = (DuracaoEvento)agendamento.DuracaoEvento,
                    TipoEvento = (TipoEvento)agendamento.TipoEvento,
                    NumeroCelular = agendamento.NumeroCelular,
                    Localizacao = agendamento.Localizacao,
                    InfoEvento = agendamento.InfoEvento,
                    Horainicio = (TimeSpan)agendamento.Horainicio,
                };

            _interface.AddBanco(agendamentoModel);


            string PrecoeHora = string.Empty;

            switch (agendamento.DuracaoEvento)
            {
                case DuracaoEvento.UmaHora:
                    PrecoeHora =  "Duração e Valor contratado : 1 Hora - R$ 250,00";
                    break;

                case DuracaoEvento.DuasHora:
                    PrecoeHora = "Duração e Valor contratado : 2 Horas - R$ 400,00";
                    break;

                case DuracaoEvento.TresHora:
                    PrecoeHora = "Duração e Valor contratado : 3 Horas - R$ 600,00";
                    break;

                case DuracaoEvento.QuatroHora:
                    PrecoeHora = "Duração e Valor contratado : 4 Horas - R$ 800,00";
                    break;
            };
           

            string mensagemWhatsapp =
                $"Olá, gostaria de confirmar o agendamento.\n\n" +
                $"Nome : {agendamentoModel.Nome}\n" +
                $"Data Evento : {agendamentoModel.DataEvento.ToString("dd/MM/yyyy")}\n" +
                $"{PrecoeHora}\n"+
                $"Horário de inicio do evento : {agendamentoModel.Horainicio}\n"+
                $"Tipo de Evento : {agendamentoModel.TipoEvento}\n" +
                $"Localização : {agendamentoModel.Localizacao}\n" +
                $"Observações {agendamentoModel.InfoEvento}\n\n" +
                $"Chave PIX : 69992955498 - Nubank - Jucimar Moraes Rodrigues Queiroz";

                

            TempData["MensagemURL"] = Uri.EscapeDataString(mensagemWhatsapp);

            TempData["SucecessAgendamento"] = "Agendamento enviado com Sucesso!!";
            return View("SucessoAgenda");
        }
    }
}

Views/Adm/Index.cshtml
@using Agendamento_de_Eventos.Enums;
@model List<AgendamentoModel>
@{
    ViewData["Title"] = "Painel Administrativo - ";
}

<h1 class="text-center h1-grupo-casamento">Painel Administrativo</h1>

@if (TempData["AgendaNull"] != null)
{
    <div class="alert alert-danger">
        @TempData["AgendaNull"]
        <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
    </div>
}
@if (TempData["SucessAgendaStatus"] != null)
{
    <div class="alert alert-success">
        @TempData["SucessAgendaStatus"]
        <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
    </div>
}

<!-- converter o Viewbag para Dictionary -->
@{
    var duracaoEvento = (Dictionary<DuracaoEvento, string>)ViewBag.NewNameDuracao;
    var tipoEvento = (Dictionary<TipoEvento, string>)ViewBag.NewNameTipoEvento;
}


<div style="margin: 0 10px 0 10px;">
<div class="table-responsive">
    <table class="display nowrap table table-striped table-agendas" id="table-agendas">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Data</th>
                <th scope="col">Duração</th>
                <th scope="col">Horário de início</th>
                <th scope="col">Tipo de Evento</th>
                <th scope="col">Telefone</th>
                <th scope="col">Localização</th>
                <th scope="col">Observações</th>
                <th scope="col">Status</th>
            </tr>
        </thead>

        <tbody>

            @if (Model != null && Model.Any())
            {
                @foreach (AgendamentoModel agendamentoModel in Model)
                {
                    <tr>
                        <td>@agendamentoModel.Nome</td>
                        <td>@agendamentoModel.DataEvento.ToString("dd/MM/yyyy")</td>
                        <td>@duracaoEvento[agendamentoModel.Duracao]</td>
                        <td>@agendamentoModel.Horainicio</td>
                        <td>@tipoEvento[agendamentoModel.TipoEvento]</td>
                        <td>@agendamentoModel.NumeroCelular</td>
                        <td>@agendamentoModel.Localizacao</td>
                        <td>@agendamentoModel.InfoEvento</td>
                        <td>
                            <form asp-controller="Adm" asp-action="AtualizarStatus" method="post" class="d-flex justify-content-center gap-2">

                                <input type="hidden" name="id" value="@agendamentoModel.Id" />

                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="StatusEvento" value="1" @(agendamentoModel.Status == StatusEvento.Concluido ? "checked" : "") />
                                    <label class="form-check-label">Concluído</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="StatusEvento" value="2" @(agendamentoModel.Status == StatusEvento.Pendente ? "checked" : "") />
                                    <label class="form-check-label">Pendente</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="StatusEvento" value="3" @(agendamentoModel.Status == StatusEvento.Cancelado ? "checked" : "") />
                                    <label class="form-check-label">Cancelado</label>
                                </div>

                                <button class="btn btn-sm btn-success" type="submit">Salvar</button>

                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
</div>

Views/Adm/Login.cshtml
@using Agendamento_de_Eventos.ViewModel
@model LoginAdmViewModel
@{
    ViewData["Title"] = "Página Inicial - ";
}

@if (TempData["ErrorLoginAdm"] != null)
{
    <div class="alert alert-danger" style="margin: 25px 5px 10px 5px;">
        @TempData["ErrorLoginAdm"]
        <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
    </div>
}

<div style="margin: 0 10px 0 10px;">
<form asp-controller="Adm" asp-action="Login" method="post">
    <div class=" mt-3 mb-3">
        <label for="Usuario" class="form-label">Usuário</label>
        <input asp-for="usuario" type="text" class="form-control">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.usuario)</span>
    </div>
    <div class="mb-3">
        <label for="Senha" class="form-label">Senha</label>
        <input asp-for="senha" type="password" class="form-control">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.senha)</span>
    </div>

    <button type="submit" class="btn btn-primary mb-4" style="padding: 13px; border-radius: 31px;">Entrar</button>
    <br />
    <a asp-controller="Home" asp-action="Index" class=" btn btn-secondary mb-4" style="padding: 13px; border-radius: 31px;">Voltar à página inicial</a>
</form>
</div>

Views/Adm/PageMensagemRestrita.cshtml
@{
    ViewData["Title"] = "Página Inicial - ";
}

<h1 class="text-center h1-grupo-casamento mt-3 mb-3"> Página somente Admin</h1>

<div style="background-color: #262626; border-radius: 1rem; margin: 0 20px 35px 20px; position: relative; top:10%;">
<p class="p-apresentacao-index">
    Página restrita somente para Admin. Clique no botão abaixo para voltar à tela inicial
</p>
</div>

<a asp-controller="Home" asp-action="Index" class="btn btn-sm btn-primary" style="padding: 11px; border-radius: 22px; margin-left:20px;">Voltar à página Inicial</a>

Views/Agendamento/Index.cshtml
@using Agendamento_de_Eventos.Enums
@using Agendamento_de_Eventos.ViewModel
@model AgendamentoViewModel
@{
    ViewData["Title"] = "Agendamento - ";
}

<h1 class=" h1-view-agendamento text-center mb-4">Agende Seu Evento</h1>

@if (TempData["ErroDataModel"] != null)
{
    <div class="alert alert-danger" style="margin: 0 5px 10px 5px;">
        @TempData["ErroDataModel"]
        <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
    </div>
}

@if (TempData["ErroDataInvalida"] != null)
{
    <div class="alert alert-danger" style="margin: 0 5px 10px 5px;">
        @TempData["ErroDataInvalida"]
        <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
    </div>
}
@if (TempData["dataReservada"] != null)
{
    <div class="alert alert-danger" style="margin: 0 5px 10px 5px;">
        @TempData["dataReservada"]
        <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
    </div>
}

<div class="espaco-form">
<form asp-controller="Agendamento" asp-action="AddEvento" method="post">

    <div class="mb-3">
        <label for="Nome" class="form-label">Digite Seu nome : </label>
        <input asp-for="Nome" type="text" class="form-control">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.Nome)</span>
    </div>

    <div class="mb-3">
        <label for="DiaEvento" class="form-label">Selecione a data do evento : </label>
        <input asp-for="DataMarcada" type="date" placeholder="Escolha a data do Evento" class="form-control">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.DataMarcada)</span>
    </div>

    <div class="mb-3">
        <label asp-for="TipoEvento" class="form-label"> Escolha o Evento : </label>
        <select asp-for="TipoEvento" class="form-select">
            <option value="">Selecione o tipo de Evento </option>
            <option value="@TipoEvento.Aniversario">Aniversário</option>
            <option value="@TipoEvento.Casamento">Casamento</option>
            <option value="@TipoEvento.EventoSocial">Evento Social</option>
            <option value="@TipoEvento.EventoCorporativo">Evento Corporativo</option>
            <option value="@TipoEvento.EventoReligioso">Evento Religioso</option>
            <option value="@TipoEvento.JantarRecepcao">Jantar e Recepção</option>
            <option value="@TipoEvento.ApresentacaoCultural">Apresentação Cultural</option>
            <option value="@TipoEvento.ApresentacaoInstitucional">Apresentação Institucional</option>
            <option value="@TipoEvento.Outro">Outro</option>
        </select>
        </label>
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.TipoEvento)</span>
    </div>

    <div class="mb-3">
        <label asp-for="DuracaoEvento" class="form-label">Escolha a Duração do Evento </label>
        <select asp-for="DuracaoEvento" class="form-select">
            <option value="">Selecione aproximadamente a Duração do Evento </option>
            <option value="@DuracaoEvento.UmaHora">1 Hora - R$ 250,00</option>
            <option value="@DuracaoEvento.DuasHora">2 Horas - R$ 400,00</option>
            <option value="@DuracaoEvento.TresHora">3 Horas - R$ 600,00</option>
            <option value="@DuracaoEvento.QuatroHora">4 Horas - R$ 800,00</option>
        </select>
        </label>
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.DuracaoEvento)</span>
    </div>

    <div class="mb-3">
        <label for="InicioEvento" class="form-label">Digite o horário de inicio do evento : </label>
        <input asp-for="Horainicio" type="time" class="form-control">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.Horainicio)</span>
    </div>

    <div class="mb-3">
        <label for="LocalizacaoEvento" class="form-label">Digite a Localização do Evento : </label>
        <input asp-for="Localizacao" type="text" class="form-control">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.Localizacao)</span>
    </div>

    <div class="mb-3">
        <label for="NumeroCelular" class="form-label">Digite seu número (Whatsapp) : </label>
        <input asp-for="NumeroCelular" type="text" class="form-control" placeholder="Ex: (xx) xxxxx-xxxx">
        <span class="texto-validacao">@Html.ValidationMessageFor(x => x.NumeroCelular)</span>
    </div>
    <div class="mb-3">
        <label for="InformacaoEvento" class="form-label">Observações</label>
        <input asp-for="InfoEvento" type="text" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary mb-4" style="padding: 15px; border-radius: 65px;">Enviar</button>
    <br />
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary mb-4" style="padding: 15px; border-radius: 65px;">Voltar à página inicial</a>
</form>
</div>

Views/Agendamento/SucessoAgenda.cshtml
@{
    ViewData["Title"] = " Finalização Agendamento - ";
}

<h1 class="text-center" style="font-weight: bold"> Seguir com o Pagamento </h1>

@if (TempData["SucecessAgendamento"] != null)
{
<div class="alert alert-success">
    @TempData["SucecessAgendamento"]
    <button type="button" class="btn-close botao-X" data-bs-dismiss="alert"></button>
</div>
}

@if (TempData["MensagemURL"] != null)
{
<a href="https://wa.me/5569992955498?text=@TempData["MensagemURL"]" target="_blank">Clique aqui para seguir com o pagamento (Via Whatsapp) </a>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial - ";
}

<section class="image-pagina-inicial">
    <h1 class="text-center">Jucimar Moraes</h1>
    <h2 class="text-center img-h2">Voz e Violão</h2>
</section>

<div data-aos="fade-up">
    <h2 class="text-center mt-4 mb-4"> Sobre Jucimar Moraes</h2>
</div>

<div data-aos="zoom-in-right" style="background-color: #262626; border-radius: 1rem; margin: 0 20px 0 20px;">

        <p class="p-apresentacao-index">
            Sou músico profissional com mais de 15 anos de experiência, atuando em apresentações ao vivo e projetos musicais diversos. Minha trajetória une sensibilidade artística, técnica musical e profissionalismo, proporcionando experiências musicais marcantes e acolhedoras para todos os públicos.
            <br/>
            <br />
            Além da atuação como cantor e instrumentista, possuo formação e vivência em musicoterapia, o que reflete diretamente na forma como conduzo cada apresentação: leitura do ambiente, escolha adequada do repertório, interação respeitosa com o público e entrega musical com emoção e equilíbrio.
            Cada show é pensado para valorizar o momento, o ambiente e as pessoas presentes.
        </p>
    </div>

<div class="img-tipos-musicas">

    <div data-aos="fade-up">
        <h2 class="text-center pt-3"> Estilos Musicais </h2>
    </div>

<div data-aos="zoom-in-left" style="position: relative; top: 10%;">

    <div class="lista-musicas">

        <div class="icone-topo text-center">
            <i class="fa-solid fa-music"></i>
        </div>

        <ul>
            <li>MPB</li>
            <li>Pop Rock Nacional</li> 
            <li>Sertanejo</li>
            <li>Xote</li>
            <li>Forró</li>
            <li>Músicas Religiosas</li>
        </ul>
    </div>
</div>
</div>

<div data-aos="fade-up">
    <h2 class="text-center mt-4 mb-4">Equipamentos</h2>
</div>

<div data-aos="zoom-in-right" style="background-color: #262626; border-radius: 1rem; margin: 0 20px 0 20px;">

    <div class="icone-topo text-center">
        <i class="fa-solid fa-sliders"></i>
    </div>

    <p class="p-apresentacao-index">
       Trabalho com equipamentos de altíssima qualidade, garantindo excelente definição sonora, volume equilibrado e alcance ideal para diferentes tamanhos de público, seja em ambientes intimistas ou eventos maiores.
    <br />
    <br />
        Todo o sistema de som é próprio, moderno e bem ajustado, proporcionando conforto acústico e qualidade profissional.
    </p>
</div>


<div class="img-lista-eventos">

    <h2 class="text-center pt-3" style="position: relative; top: 4%;"> Tipos de Eventos </h2>

    <div data-aos="zoom-in-left" style="position: relative; top: 10%" class="lista-eventos">

        <div class="icone-topo text-center">
            <i class="fa-solid fa-calendar-check"></i>
        </div>

        <ul>
            <li>Casamentos (cerimônia e recepção)</li>
            <li>Aniversários</li>
            <li>Eventos sociais</li>
            <li>Eventos corporativos</li>
            <li>Confraternizações</li>
            <li>Jantares e recepções</li>
            <li>Eventos religiosos</li>
            <li>Apresentações culturais e institucionais</li>
            <li>(Outros formatos podem ser avaliados sob consulta)</li>
            </ul>
    </div>
</div>

<div data-aos="fade-up">
<h2 class="text-center mt-4 mb-4"> Duração e Valores </h2>
</div>

<div class="horas-grid mb-5">
    <div class="hora-card">
        <span class="tempo">1 Hora</span>
        <span class="valor">R$ 250</span>
    </div>

    <div class="hora-card">
        <span class="tempo">2 Horas</span>
        <span class="valor">R$ 400</span>
    </div>

    <div class="hora-card">
        <span class="tempo">3 Horas</span>
        <span class="valor">R$ 600</span>
    </div>

    <div class="hora-card">
        <span class="tempo">4 Horas</span>
        <span class="valor">R$ 800</span>
    </div>
</div>

<div class="text-center button-pagina-inicial">
    <a class="btn btn-primary" asp-controller="Agendamento" asp-action="Index" style="padding: 15px; border-radius: 65px;">Agende Seu Evento</a>
</div>
<div class="text-center button-pagina-inicial">
    <a class="btn btn-primary" asp-controller="Home" asp-action="GrupoCasamento" style="padding: 15px; border-radius: 65px;">Grupo Musical para Casamentos</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Agendamento de Eventos</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Unna:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Agendamento_de_Eventos.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.3.6/datatables.min.css" rel="stylesheet" integrity="sha384-kl/GL6Bf/pDfgmgFKZ4XzwANesvO6EBSlfZFyztPhoFTDcL7H8rdOAYRXwGyOfCK" crossorigin="anonymous">
        
</head>
<body class="min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark custom-navbar box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agendamento de Eventos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Agendamento" asp-action="Index">Agendamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="GrupoCasamento">Grupo L’Acordes</a>
                        </li>
                        <a asp-controller="Adm" asp-action="Login" class="btn btn-primary button-paineladm-index">Painel Administrativo</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer-site text-light py-2">
        <div class="container-fluid text-center">
            <small>
            © 2026 Jucimar Moraes. Todos os direitos reservados.
            <br />
            Desenvolvido por Rafael Feitosa
            </small>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.3.6/datatables.min.js" integrity="sha384-18AyDs6cawP/DD9zgSqUrUeo+moSbSkFr4pe43ttGuiPDGYQitDsvTjtrDnVzrZg" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>